Added images
asam-ev/OpenMATERIAL pull request #218
Opened 2024-12-05 13:11 UTC by ACMackenthun

## Describe your changes

Add a description of the changes proposed in the pull request.

**Some questions to ask**:

- What is the change?
- What does it fix?
- Is this a bug fix or a feature? Does it break any existing functionality or force me to update to a new version?
- How has it been tested?

## Issue ticket number and link

Add a reference to a related issue.

## Mention a member

Add @mentions of the person or team responsible for reviewing the proposed changes.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code/documentation.
- [ ] My changes generate no new warnings during the documentation generation.

2024-12-09 12:48 UTC, ACMackenthun commented on content/_images/Grp_Buildings.svg
I added a first draft of the images for the different environment structures. The ones where I use an overlay look too blurry in the preview and also have a different size than on my artwork. I will make sure that the sizes, blur, and highlighting strategy are consistent for the final review.

@ClemensLinnhoff: Could you please check whether the first draft goes into the right direction? For consistency reasons, I used the same perspective as in OpenDRIVE, see https://publications.pages.asam.net/standards/ASAM_OpenDRIVE/ASAM_OpenDRIVE_Specification/latest/specification/14_signals/14_01_introduction.html. However, this 3D perspective makes it hard to place the coordinate systems with the correct orientation.

2024-12-09 13:01 UTC, ClemensLinnhoff requested changes
The images look very good.
The coordinate origins should be in the center of the bounding box of the object, projected to the ground, if not otherwise specified (we need to add this to the general section).
Here, this mainly affects building, vegetation, and Road Objects (the poles of traffic signs) The origins of the signs and lights are correct.

2024-12-09 13:13 UTC, ACMackenthun commented on content/geometry/object-environment/environment-structure.adoc
> +image::Grp_Environment_Objects.svg[,600]
I added the image and tried to position the coordinate positions in the center of the bounding box on the ground. Do you think that this is clear enough or should I come up with a draft where I visualize the bounding boxes?

2024-12-09 15:05 UTC, ClemensLinnhoff commented on content/geometry/object-environment/environment-structure.adoc
> +image::Grp_Environment_Objects.svg[,600]
I think that's okay. But [Grp_Buildings.svg](https://github.com/asam-ev/OpenMATERIAL/pull/218/files#diff-d07dcf9475939da7c0c364a68f9b783137961328bf3ec7ff676d58f773079410) and [Grp_Road_Objects.svg](https://github.com/asam-ev/OpenMATERIAL/pull/218/files#diff-47774107c28d1a676c6d448651e0f9d521494cfe2e443410816dc1d935cb4394) still need to be changed

2024-12-09 17:45 UTC, ACMackenthun commented on content/_images/Grp_Environment_Objects.svg
I updated the images for environment objects, buildings, and vegetation, where I added bounding boxes to show the correct position of the coordinate origin.

2024-12-09 17:49 UTC, ACMackenthun commented on content/_images/Grp_Road_Objects.svg
I updated the road object image and moved the origin of the coordinate system to the ground. In combination with the text, the reader should know that the sign and traffic light itself is not part of the road object. However, I could also overlay the sign face/lights or add additional road objects like safety bollards or a guardrail. What would be a good example?

2024-12-09 17:52 UTC, ClemensLinnhoff commented on content/geometry/object-environment/environment-structure.adoc
> +image::Grp_Environment_Objects.svg[,600]
Looks very good, thank you!

2024-12-09 17:57 UTC, ClemensLinnhoff commented on content/_images/Grp_Road_Objects.svg
Yes, could you gray out the sign and traffic light in [Grp_Road_Objects.svg](https://github.com/asam-ev/OpenMATERIAL/pull/218/files#diff-47774107c28d1a676c6d448651e0f9d521494cfe2e443410816dc1d935cb4394)?
And maybe you can add a traffic cone (from a construction site) as another object.

In [Grp_Sign.svg](https://github.com/asam-ev/OpenMATERIAL/pull/218/files#diff-68bf578eb40d9013f0a45f3678b442ff3f356508d16660c18b16ea2ee617901e) and [Grp_Traffic_Light.svg](https://github.com/asam-ev/OpenMATERIAL/pull/218/files#diff-fe8707f26fac36d73ff3ca26e5b76c3aa16948b3fac29e968289474d6ae5ba8c) the sign and lights are grayed out. Could you revert that? It might be misleading.

2024-12-09 17:57 UTC, ClemensLinnhoff commented on content/_images/Grp_Environment_Objects.svg
That looks good now.

2024-12-09 18:27 UTC, ACMackenthun commented on content/_images/Grp_Road_Objects.svg
Sure, I added cones and grayed out the sign and light in [Grp_Road_Objects.svg](https://github.com/asam-ev/OpenMATERIAL/pull/218/files#diff-47774107c28d1a676c6d448651e0f9d521494cfe2e443410816dc1d935cb4394).

I also removed the overlay in [Grp_Sign.svg](https://github.com/asam-ev/OpenMATERIAL/pull/218/files#diff-68bf578eb40d9013f0a45f3678b442ff3f356508d16660c18b16ea2ee617901e) and [Grp_Traffic_Light.svg](https://github.com/asam-ev/OpenMATERIAL/pull/218/files#diff-fe8707f26fac36d73ff3ca26e5b76c3aa16948b3fac29e968289474d6ae5ba8c) to avoid misunderstandings.

2024-12-09 18:34 UTC, ACMackenthun commented on content/_images/Grp_Drivable_Area.svg
I reused these images from OpenDRIVE even though they do not have the same style as the other images of the topic. Do you want me to redraw them and to align the style with the other OpenMATERIAL images?

2024-12-10 06:57 UTC, ClemensLinnhoff commented on content/_images/Grp_Road_Objects.svg
The coordinate frame on the traffic cone is not right handed. And please add the coordinates to both cones.

2024-12-10 06:58 UTC, ClemensLinnhoff commented on content/_images/Grp_Drivable_Area.svg
Yes, good idea. Then the style matches. You can probably just reuse the road you already drew for some of the other images.

2024-12-10 10:38 UTC, ACMackenthun commented on content/_images/Grp_Road_Network.svg
Refactored images of road network, drivable area, and sidewalk to match the style of the road object and signal images. I decided to remove some of the details of the OpenDRIVE images and hope that they still contain the relevant information for OpenMATERIAL. Just let me know if you have any remarks or additional requirements.

2024-12-10 10:40 UTC, ACMackenthun commented on content/_images/Grp_Road_Network.svg
I just noticed the wrong orientation of the y-axis. Will fix it in a minute

2024-12-10 11:16 UTC, ACMackenthun commented on content/_images/Grp_Drivable_Area.svg
I changed the style and also doublechecked the orientation of the x- and y-axes. All images use the vanishing point in the center of the image as true north, which is why all y-axes have a slightly different angle. The x-axis always points to the east.

We probably need to change some coordinate origins, e.g. the one for road network and drivable area, where I was not sure about the correct position.

2024-12-10 11:51 UTC, ClemensLinnhoff commented on content/_images/Grp_Terrain.svg
I just noticed that the z axis needs to point up here.

2024-12-10 13:25 UTC, ACMackenthun commented on content/_images/Grp_Terrain.svg
Originally, I picked this picture because of the clear terrain structure with its multiple shadings and without buildings. Because of the satellite view, I placed x and y on the ground to show that they point straight to the north and east. z was meant to point out of the plane, to the viewer, who is positioned in the air.

However, I see your point, and agree that the top-view perspective is misleading. I committed a new version where I added fake tiles to simulate a 3D perspective. Does that work for you?

Maybe we should replace the underlying image completely, but I did not yet find a public domain image of a digital terrain model with an appropriate perspective. Do you have an image that we could use for this purpose?

2024-12-10 13:32 UTC, merged