Introduction update to add clarity about the Material/Geometry compliance of the standard
asam-ev/OpenMATERIAL pull request #248
Opened 2024-12-16 14:10 UTC by AsamDiegoSanchez

## Describe your changes

Further information added in the introduction about how the standard is structured and how the users can be conform with.

## Issue ticket number and link

https://github.com/asam-ev/OpenMATERIAL/issues/169

## Checklist before requesting a review

- [X] I have performed a self-review of my code/documentation.
- [X] My changes generate no new warnings during the documentation generation.

2024-12-16 15:49 UTC, ClemensLinnhoff commented
To  me it was a bit unstructured, because in the first part the different compliance options were already introduced but then there was a spearate section about it. Also, introducing a sub-headline after a text is not allowed according to the editorial guide.

So I took the liberty of restructuring this a little bit. Would this be okay for you @AsamDiegoSanchez ?

2024-12-17 06:53 UTC, ClemensLinnhoff approved these changes

2024-12-17 22:10 UTC, LudwigFriedmann reviewed
Just some minor remarks ...

2024-12-18 20:25 UTC, LudwigFriedmann requested changes
Sorry I missed to request changes

2024-12-19 06:20 UTC, AsamDiegoSanchez reviewed
Signed-Off by: Diego Sánchez <diego.sanchez@asam.net>

2024-12-19 06:20 UTC, AsamDiegoSanchez commented on content/general-docs/introduction.adoc
> +* *Geometry*: This chapter contains node hierarchies for different object classes. These structures use a uniform naming scheme and coordinate definitions to enable the exchange of 3D models between
Updated

2024-12-19 06:20 UTC, AsamDiegoSanchez commented on content/general-docs/introduction.adoc
> +* *Geometry Chapter Compliance*: Users who primarily deal with geometric data, such as 3D models, shapes, or spatial structures, can claim compliance with the Geometry chapter independently.
done

2024-12-19 10:06 UTC, merged