67 emissivity
asam-ev/OpenMATERIAL pull request #86
Opened 2024-09-05 11:11 UTC by DavidJRitter904

## Describe your changes

As discussed in Meeting 04.09.2024:

- [ ] Add emissivity data as object type with separated emissivity and temperature values.

**Some questions to ask**:

- What is the change?
- What does it fix?
- Is this a bug fix or a feature? Does it break any existing functionality or force me to update to a new version?
- How has it been tested?

## Issue ticket number and link

Closes issue [#67](https://github.com/asam-ev/OpenMATERIAL/issues/67).

## Mention a member

Add @mentions of the person or team responsible for reviewing the proposed changes.

## Checklist before requesting a review

- [ ] I have performed a self-review of my code/documentation.
- [ ] My changes generate no new warnings during the documentation generation.

2024-09-06 05:56 UTC, ClemensLinnhoff commented
Do we need the possibility to have multiple value pairs of temperature and emissivity? In this implementation, only two fixed values are possible.

2024-09-06 08:36 UTC, DavidJRitter904 commented
> Do we need the possibility to have multiple value pairs of temperature and emissivity? In this implementation, only two fixed values are possible.

It gives the possibility to add your own emissivity data. 
We would anyway provide the table as in the legacy branch at T=300.0 K with a fixed emissivity value then.

2024-09-06 12:07 UTC, DavidJRitter904 commented
A further problem of the table given in the legacy for emissivity is, that the value is not fixed for all materials but includes ranges.

[Legacy emissivity table](https://www.engineeringtoolbox.com/emissivity-coefficients-d_447.html)

2024-09-11 13:35 UTC, ClemensLinnhoff commented
> Do we need the possibility to have multiple value pairs of temperature and emissivity? In this implementation, only two fixed values are possible.

Group decision: No lookup table with temperature, angle and wavelength for now. This could be added in a later release.

2024-09-12 10:31 UTC, ClemensLinnhoff commented
> We use the **_hemispherical total emissivity_** which considers full emission over all wavelengths, directions and polarization for a given particular temperature:   ε(T)

Could you add that to the description?
And please also add the source field analog to #82.

2024-09-16 15:09 UTC, DavidJRitter904 commented
@ClemensLinnhoff I have updated again the branch and resolved the new merge conflicts. 
The emissivity data should be here now, including the elasticity and density data already pulled from the main. 👍

2024-09-16 15:30 UTC, ClemensLinnhoff approved these changes

2024-09-16 17:37 UTC, drsftx73 commented
@ClemensLinnhoff with Emissive materials, a custom shader (or modifications to a simulator's 'standard' shader) will be required for this to look correct. Also additional textures, point/spot lights will be required as well. Is this outside of our scope?

2024-09-17 05:48 UTC, ClemensLinnhoff commented
> @ClemensLinnhoff with Emissive materials, a custom shader (or modifications to a simulator's 'standard' shader) will be required for this to look correct. Also additional textures, point/spot lights will be required as well. Is this outside of our scope?

This is not about conventional light sources. This is about thermal radiation.

2024-09-18 13:27 UTC, ClemensLinnhoff requested changes

2024-09-18 13:27 UTC, ClemensLinnhoff commented on examples/example_material.xomp
> +        "emissivity": 0.07,
```suggestion
        "emissivity_coefficient": 0.07,
```

2024-09-18 13:27 UTC, ClemensLinnhoff commented on schemas/material_schema.json
> +            "emissivity": {
```suggestion
            "emissivity_coefficient": {
```

2024-09-18 14:31 UTC, ClemensLinnhoff commented on examples/example_material.xomp
> +        "emissivity": 0.07,
It was discussed in the material group, that emissivity_coefficient would be a bit more accurate.

2024-09-19 09:37 UTC, KimuraDIVP commented
I just want to confirm that this "emmisivity" is for the far infrared rays sensor, right?

2024-09-19 09:59 UTC, ClemensLinnhoff commented
Needs to be adapted to new naming convention, after #110 is merged,

2024-09-19 09:59 UTC, ClemensLinnhoff commented
> I just want to confirm that this "emmisivity" is for the far infrared rays sensor, right?

Mainly for infrared cameras.

2024-09-19 23:52 UTC, KimuraDIVP approved these changes

2024-09-24 07:57 UTC, ClemensLinnhoff approved these changes

2024-09-24 07:57 UTC, merged